name: reviewed
favicon: null
layout_spectrum: 0.9551986146252602
typography_spectrum: 0.22724251099862158
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5111452369019389
  lightness: 0.10477546113543212
  saturation: 0.5470994014758617
  rhythmicContrast: 0.979618841316551
purpose: []
