name: reviewed
favicon: null
layout_spectrum: 0
typography_spectrum: 0.10853
title: The Grid Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2d9de'
    - '#292148'
    - '#90a6b1'
    - '#6f8ca0'
    - '#3a474a'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
