name: reviewed
favicon: null
layout_spectrum: 1
typography_spectrum: 0.62937
title: The Grid Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2d9de'
    - '#292148'
    - '#90a6b1'
    - '#6f8ca0'
    - '#3a474a'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
